import { query, queryOne } from '../db/client';
import { ai } from '../services/ai/openrouter';
import { getAllActiveSites } from './scheduler';
import { logger } from '../utils/logger';
import { Resend } from 'resend';
import dayjs from 'dayjs';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function sendWeeklyReport(): Promise<void> {
  const superAdmin = await queryOne<any>(
    `SELECT email, name FROM engine.admin_users WHERE role = 'super_admin' AND is_active = true LIMIT 1`
  );
  if (!superAdmin?.email) { logger.warn('[reports] No super admin email configured'); return; }

  const sites = await getAllActiveSites();
  const from = dayjs().subtract(7, 'day').format('YYYY-MM-DD');
  const to = dayjs().format('YYYY-MM-DD');

  const siteReports = [];
  let totalRevenue = 0;
  let totalOrders = 0;

  for (const site of sites) {
    const s = site.schema_name;
    const stats = await queryOne<any>(
      `SELECT
         COUNT(*) FILTER (WHERE payment_status = 'paid') as orders,
         COALESCE(SUM(total) FILTER (WHERE payment_status = 'paid'), 0) as revenue,
         COALESCE(AVG(total) FILTER (WHERE payment_status = 'paid'), 0) as aov,
         COUNT(*) FILTER (WHERE payment_method = 'cod') as cod_orders
       FROM ${s}.orders WHERE created_at >= $1 AND created_at <= $2`,
      [from, to + ' 23:59:59']
    );

    totalRevenue += parseFloat(stats?.revenue || '0');
    totalOrders += parseInt(stats?.orders || '0');
    siteReports.push({
      name: site.name,
      domain: site.domain,
      orders: stats?.orders || 0,
      revenue: parseFloat(stats?.revenue || '0').toFixed(2),
      aov: parseFloat(stats?.aov || '0').toFixed(2),
    });
  }

  // AI-generated summary
  const aiSummary = await ai.assistant([
    { role: 'system', content: 'Generate a brief, business-like weekly summary in 2-3 sentences.' },
    { role: 'user', content: `Weekly data: ${totalOrders} total orders, ₹${totalRevenue.toFixed(2)} total revenue across ${sites.length} sites. Highlight key metrics.` }
  ]).then(r => r.content).catch(() => 'Weekly report generated.');

  const sitesTable = siteReports.map(s =>
    `<tr><td>${s.name}</td><td>₹${s.revenue}</td><td>${s.orders}</td><td>₹${s.aov}</td></tr>`
  ).join('');

  try {
    await resend.emails.send({
      from: `Meesho Commerce OS <${process.env.EMAIL_FROM}>`,
      to: superAdmin.email,
      subject: `📊 Weekly Report — ${dayjs().format('DD MMM YYYY')} | ₹${totalRevenue.toFixed(0)} Revenue`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto; padding: 20px;">
          <h1 style="color: #4F46E5;">📊 Meesho Commerce OS — Weekly Report</h1>
          <p style="color: #666;">${from} to ${to}</p>
          <p>${aiSummary}</p>
          <h2>Total Performance</h2>
          <p>💰 <strong>Revenue: ₹${totalRevenue.toFixed(2)}</strong></p>
          <p>📦 <strong>Orders: ${totalOrders}</strong></p>
          <h2>Per-Site Breakdown</h2>
          <table border="1" cellpadding="8" style="border-collapse: collapse; width: 100%;">
            <tr style="background:#4F46E5; color:white;"><th>Site</th><th>Revenue</th><th>Orders</th><th>AOV</th></tr>
            ${sitesTable}
          </table>
          <p style="color: #999; font-size: 12px; margin-top: 20px;">Generated by Meesho Commerce OS AI</p>
        </div>
      `,
    });
    logger.info(`[reports] Weekly report sent to ${superAdmin.email}`);
  } catch (err: any) {
    logger.error('[reports] Email failed', { error: err.message });
  }
}
